name: 'SwitchUbuntuGccGxxVersion'
description: 'To Switch the GCC/G++ Version on Ubuntu'
inputs:
  TargetVer:
    description: 'The Target Version to Apply on Your Github Action'
    required: true
    default: '12'
runs: |
    echo "------------Check current GCC GXX Version Before Switch------------"
    gcc --version
    g++ --version
    echo "------------------------------GCC_GXX------------------------------"
    echo "---------------------Install GCC GXX Version ${{ inputs.TargetVer }}--------------------"
    sudo -E apt-get -qq update
    sudo -E apt-get -qq install gcc-${{ inputs.TargetVer }} g++-${{ inputs.TargetVer }}
    echo "------------------------------GCC_GXX------------------------------"
    echo "--------------------Switch gcc/g++ Version to ${{ inputs.TargetVer }}-------------------"
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ inputs.TargetVer }} 50
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ inputs.TargetVer }} 50
    sudo update-alternatives --set gcc /usr/bin/gcc-${{ inputs.TargetVer }}
    sudo update-alternatives --set g++ /usr/bin/g++-${{ inputs.TargetVer }}
    echo "------------------------------GCC_GXX------------------------------"
    echo "-------------Check current GCC GXX Version After Switch------------"
    gcc --version
    g++ --version
    echo "------------------------------GCC_GXX------------------------------"
