name: Test Switch GCC/G++ Version

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  SwitchGCCGXX:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Switch GCC/GXX Version
        uses: xylz0928/SwitchUbuntuGccGxxVersion@v1.0.6
        with:
          TargetVer: '11'
